### PR TITLE
feat: support using docker secrets for jotta token

### PR DESCRIPTION
**Pull request by haakemon**
A small improvement to also support using docker secrets for the auth token

### CODE REVIEW

**Comment by bluet** [comment]
Hi @haakemon thanks for the PR.

As there are many unrelated changes in this PR, I've manually cherry-picked in https://github.com/bluet/docker-jottacloud/commit/f1cd24d5af20fcada9d1412f049f6924c7a774d8 , would you mind checking it and see if that satisfied your needs?

Thanks!

**Comment by bluet** [comment]
@all-contributors please add @haakemon for docker secret support #1

**Comment by bluet** [comment]
@all-contributors please add @haakemon for code and ideas

**Comment by haakemon** [comment]
Ah, I didnt notice I created the PR from my main branch 🤦 thats why there were so many unrelated changes. 

Great that you added support for it 😁 closing this.

**Pull request closed without merging**
